### ISSUE TITLE
Falta en menú operadores el f_Stock_a_Fecha.fmx

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#10]
Falta en menú operadores el f_Stock_a_Fecha.fmx
![screenhunter_163 nov 23 17 27](https://cloud.githubusercontent.com/assets/23344175/20577753/8bc04dfc-b1a2-11e6-92cf-aca91acd2962.jpg)

**Comment by MarceloBellaera** [comment]
Estaría faltando el fmx  Interbaires/Operaciones_sis/f_stock_fecha

**Comment by rleuzzi** [comment]
Listo, volver a revisar.
