### ISSUE TITLE
Error al ejecutar interface Evolucion-PRIORIDAD

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#12]
En este caso , da el error Ora-00936.  Si lo corremos en el OAS  (forms 10) funciona bien. Todo indicaria que es dentro de la PU  GEN_INTERFACE , cuando quiere recorrer el cursor  cur_arr

Menu Interbaires/Administracion/Presupuesto/Evolucion de stock
Form f_interfaz_evolucion.

**Comment by rleuzzi** [comment]
Este lo estan usando?, continua con el error?. Podran confirmar.

**Comment by marisacoria** [comment]
Hola si esto se utiliza y te adjunto documento donde se planta en el código, y te puse cual es la opción que falla (opción Evolucion)
[Evolucion stock.docx](https://github.com/leoponti/dufry/files/727846/Evolucion.stock.docx)

**Comment by marisacoria** [comment]
Desde el acceso :Menu Interbaires/Administracion/Presupuesto/Evolucion de stock
 Form f_interfaz_evolucion.

**Comment by marisacoria** [comment]
Hola Ruben, tenes idea si esto se podrá revisar?

**Comment by rleuzzi** [comment]
Bueno, después de hacer varias pruebas se confirma que a ese cursor no le gusta el hint RULE. Es raro porque hay otros cursores con este hint en el mismo procedure. Testeamos el query y funciona incluso algo mas rápido sin el hint así que lo quitamos y genero el archivo sin errores.

Volver a testear.

**Comment by marisacoria** [comment]
Perfecto! cerralo!
