### ISSUE TITLE
No permite cargar interfaces Excel

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#13]
Hola.
No funcionó la carga de datos desde un archivo Excel.
Este tipo de ingreso de datos se utilizan en varios forms.
Paso un ejemplo puntual.
Sistema Comercial_logistica Ecuador
Menú principal /Gestion Mercaderia/niveles de exhibicion
No da ningun error pero no carga nada...
Trato de ajuntar el archivo Excel de ejemplo de este caso, pero este sistema no me lo permito x lo tanto paso una imagen del mismo ya que es muy sencillo.
Gracias

![screenhunter_164 nov 24 11 44](https://cloud.githubusercontent.com/assets/23344175/20606619/efac96be-b250-11e6-9e34-4d3b466fe6fa.jpg)

![19 nov 24](https://cloud.githubusercontent.com/assets/23344175/20606706/7f0b49ae-b251-11e6-8d85-33a1637c568f.jpg)

**Comment by rleuzzi** [comment]
Por favor adjuntar imagen de la consola Java. Muchas gracias!!!

**Comment by ppalavezzati** [comment]
![screenhunter_165 dec 01 12 23](https://cloud.githubusercontent.com/assets/23344175/20799565/4f49adf8-b7c1-11e6-9091-b260b6a3c735.jpg)

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by MarceloBellaera** [comment]
Sin cambios , no hace nada ni hay mensaje de error. Si queres ponele mensajes dentro del proceso para que veamos donde se corta.

**Comment by rleuzzi** [comment]
Probaron el de ecuardor. Ahi les copio el que modificamos a la carpeta de ecuador (quedo solo en la carpeta de Uruguay). Volver a testear en 5'

**Comment by ppalavezzati** [comment]
Probé en Ecuador Ok ¡
