### ISSUE TITLE
Objetos a  Remigrar

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#14]
Te paso la lista por aquí para hacer el seguimiento pero te mando los archivos por correo:

**Interbaires/CTC**

frmliquidaciones.fmb
frmpresentaciones_Nuevo.fmb
frmconciliapagoautomatico.fmb

**Interbaires/Administracion**
interfac.fmb
imp_seme.fmb
imp_mens.fmb
imp_sema.fmb

**InterBaires/Reportes**
FACT_OAS_CHAR_PDF.rdf
r_tr_cnp_fch.rdf

**Ecuador/Comercial_Logistica**
f_comprobante.fmb

Espero que eso sea todo.

**Comment by MarceloBellaera** [comment]
Tambien necesitamos remigrar estos:

mensual.rdf
mensual_pdf.rdf
semanale.rdf
semanale_pdf.rdf
semestral.rdf
semestral_pdf.rdf
SEMLOCAL2.rdf
SEMLOCAL2_pdf.rdf

Todos de Interbaires.

**Comment by rleuzzi** [comment]
Listo, todo migrado y publicado.

**Comment by leoponti** [comment]
Confirmar que ya se encuentra Solucionado para cerrar
