### ISSUE TITLE
Falta compilar un fmb

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#17]
Hola Ruben , Leo , estaría faltando el frmventastotalescajero.fmx , me fije y solo esta el .fmb

Nos avisan cuando este listo
Gracias

**Comment by rleuzzi** [comment]
Hola, al compilar en PROD da error de TNS los dblinks ventas.cajeros@link_baires_dp c, personal.empleado@link_baires_dp.

**Comment by MarceloBellaera** [comment]
Ruben , corta todo lo que tenga que ver con el link , esta discontinuiado

**Comment by rleuzzi** [comment]
Listo, volver a revisar.
