### ISSUE TITLE
Llamada a Reporte

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#18]
El form f_lst_picking de Interbaires/Operaciones_sis   tiene llamadas  en varios lugares con extension.rep

reporte('**picking_ord_v3.rep**',:AGRUPADOS.agrupado_seleccionado_CV,:archivo_pdf_cv, vMailConValor,vcdeposito);

Podran corregirlo ?

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by ppalavezzati** [comment]
Test OK.
