### ISSUE TITLE
Llamada a  reporte reservas_WEB_x_fecha.rep

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#19]
En el form reserva_web_x_fecha de InterBaires/Logistica/Reposicion tiene una llamada a reporte .REP

PROCEDURE emite_reporte IS 
 
		nom_rep varchar2(30); 
		param   varchar2(250); 
		pl_id   paramlist; 
 
BEGIN 
		nom_rep := '**reservas_WEB_x_fecha.rep**'; 
		 
		pl_id := Get_Parameter_List('LstVal'); 
		 
		IF NOT Id_Null(pl_id) THEN 
				Destroy_Parameter_List( pl_id ); 
		END IF; 
		 
		pl_id := Create_Parameter_List('LstVal'); 
		 
		Add_Parameter(pl_id,'PRINTJOB',text_PARAMETER,'NO'); 
		Add_Parameter(pl_id,'PARAMFORM',text_PARAMETER,'NO'); 
		Add_Parameter(pl_id,'DESTYPE',text_PARAMETER, 'PREVIEW'); 
		Add_Parameter(pl_id,'F_DESDE',text_PARAMETER,to_char(:fecha_desde,'ddmmyyyy') ); 
		Add_Parameter(pl_id,'F_HASTA',text_PARAMETER,to_char(:fecha_hasta,'ddmmyyyy') ); 
		 
		llamar_reporte(REPORTS, nom_rep, SYNCHRONOUS, RUNTIME,FILESYSTEM, pl_id, NULL); 
		 
		Destroy_Parameter_List( pl_id ); 
END;

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by MarceloBellaera** [comment]
Test OK
