### ISSUE TITLE
Error al cargar archivo de presentaciones TC

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#20]
![screenhunter_201 dec 07 13 32](https://cloud.githubusercontent.com/assets/23344175/20976687/0e3e498e-bc82-11e6-8bb5-f527d240b797.jpg)

**Comment by rleuzzi** [comment]
Lo testeamos desde aqui (corriendo obvio el form del server) y funciono ok. Por favor validen permisos sobre los directorios y los archivos.

![image](https://cloud.githubusercontent.com/assets/14017610/20979886/2b2cc77c-bc8d-11e6-9eff-03c33d58ceee.png)

**Comment by MarceloBellaera** [comment]
Test OK
