### ISSUE TITLE
No trae el Nombre del CAjero

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#21]
[ERR_TEST_FRMVENTASTOTALESCAJERO.docx](https://github.com/leoponti/dufry/files/637219/ERR_TEST_FRMVENTASTOTALESCAJERO.docx)

**Comment by rleuzzi** [comment]
Me pidieron quitara los dblinks y esos recuperaban el nombre (recordar daba error de tns al compilar). Indicar como proceder.

**Comment by marisacoria** [comment]
Hola , el tema  es que esta comentado la parte que referencia al link y también la parte que no referencia al  link que seria para empresa 1

**Comment by rleuzzi** [comment]
No solo comentamos los query al dblink:

![image](https://cloud.githubusercontent.com/assets/14017610/20978593/2ba87156-bc88-11e6-992b-ca21be7e1e24.png)

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by marisacoria** [comment]
Funciona ok
