### ISSUE TITLE
Timeout ? del sistema pasado un tiempo 

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#23]
Consulta ,cuando s
[Err_Time out.docx](https://github.com/leoponti/dufry/files/637702/Err_Time.out.docx)
e deja una pantalla abierta por ejemplo de Reportes y pasado un tiempo sin utilizar aparece el mensaje

**Comment by rleuzzi** [comment]
Si, es así por defecto. Se puede configurar el tiempo de timeout.
