### ISSUE TITLE
Dos reportes a re-migrar

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#24]
Hola Ruben , como andas ¿? Disculpa que te joda , estos dos reportes los  tuvimos que modificar sobre la  marcha . Los podrás  remigrar?  Son de Interbaires.  ( Van los archivos por mail a Ruben )

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by leoponti** [comment]
Confirmar que esta solucionado para cerrar
