### ISSUE TITLE
VENTAS-Al leer excel Ora 305501-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#26]
[Enviar revision.docx](https://github.com/leoponti/dufry/files/657248/Enviar.revision.docx)

**Comment by marisacoria** [comment]
Esto es en el Sistema de Ventas , acceso Stock exhibición/carga por producto

**Comment by marisacoria** [comment]
Hola Leo , Ruben , tenemos prioridad con esta pantalla , Marcelo me comento que en DFC tenían el mismo problema por lectura del Excel y uds modificaron la librería , ahora resulta que el tema esta en Interbaires, por ahí la librería de IB precisa la misma solución
gracias
[VENTAS_excel Niveles.docx](https://github.com/leoponti/dufry/files/714302/VENTAS_excel.Niveles.docx)

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by marisacoria** [comment]
YES!!!! THANKS !! OBRIGADO!
