### ISSUE TITLE
Sistema Compra Anticipada

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#27]
Hola aca les mando el documento , cuando se quiere imprimir no lo reconoce al reporte
[control ccaa_enviar.docx](https://github.com/leoponti/dufry/files/661916/control.ccaa_enviar.docx)

**Comment by rleuzzi** [comment]
Por lo que vemos este form lanza el reporte "r_vale_transferencia_ccaa" y en la web vemos que ejecuto correctamente.
![image](https://cloud.githubusercontent.com/assets/14017610/21390057/9820d7c0-c763-11e6-9a95-aca2b382245f.png)

**Comment by marisacoria** [comment]
Te  fijaste el documento que les  pase y probaron el imprimir y te salio el reporte? o te estas fijando solo del servidor de reporte ?, el tema que por ahí desde otra aplicación se disparo eso, podrias hacer la misma prueba que esta en el  documento ?
[Uploading control ccaa_caso_enviar.docx…]()
