### ISSUE TITLE
Test sistema de Inventarios IB

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#28]
Da error al emitir el reporte PDF.
![menu](https://cloud.githubusercontent.com/assets/23344175/21351798/5b40976c-c69d-11e6-9d73-f3c1fb1ba66c.jpg)
![form_afectado](https://cloud.githubusercontent.com/assets/23344175/21351800/5c72b21e-c69d-11e6-9a18-c1620187645e.jpg)
![error](https://cloud.githubusercontent.com/assets/23344175/21351805/5e6d7f40-c69d-11e6-9a01-bbf34461e245.jpg)

**Comment by rleuzzi** [comment]
Volver a revisar. Se agrego to_date a campos char para evitar error de formato en fecha.

![image](https://cloud.githubusercontent.com/assets/14017610/21390288/fbaca868-c764-11e6-8094-ae57c831f540.png)

**Comment by ppalavezzati** [comment]
Listo ahora salio el PDF.
Gracias.
