### ISSUE TITLE
Generacion de Archivo para Cajas - 

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#3]
Este form no genero el archivo en el path que muestra en pantalla. Si bien no dio erro no sabemos donde esta el archivo.
Es del menu Operaciones_sist  opcion Interface - Generasr novedad de articulos.

![screenhunter_34 nov 09 17 36](https://cloud.githubusercontent.com/assets/23343058/20153846/6618ad60-a6a3-11e6-832c-817e9c7b7fe9.jpg)

**Comment by rleuzzi** [comment]
El archivo se genero en el disco temporal del Linux.

![image](https://cloud.githubusercontent.com/assets/14017610/20178481/20436cd4-a730-11e6-8430-550399c58d47.png)

**Comment by MarceloBellaera** [comment]
Seguimos por  aca...    Pero deberia copiarlo al  cliente  por FTP , hay algo a tener en cuenta con esto ? Algo que haya cambiado ??

**Comment by rleuzzi** [comment]
Por favor subir print screen de la consola Java.

**Comment by MarceloBellaera** [comment]
no tenemos el icono de la consola en la barra , como la abrimos ?

**Comment by rleuzzi** [comment]
Cuando ejecutan el form, entre los residentes deberia aparecer el icono de la consola. Si no aparece, antes de arrancar el form van a panel de control->Java->Solapa Seguridad->Consola de Java->Ver Consola

**Comment by MarceloBellaera** [comment]
![screenhunter_36 nov 10 11 19](https://cloud.githubusercontent.com/assets/23343058/20180204/3b904cca-a738-11e6-972b-5c992e252ac0.jpg)

**Comment by rleuzzi** [comment]
Por lo que vemos en el codigo, necesita un subdirectorio "BKP". Podran confirmar esto asi creamos el subdirectorio en el linux?.

**Comment by MarceloBellaera** [comment]
Si , se nos paso ese detalle. En realidad habria que crear las carpetas BKP ; CAR ; PDE; GUA ;MEND; CORD; BARI;AEP y EZE

Gracias.

**Comment by rleuzzi** [comment]
Listo volver a testear. Recordar modificar el valor de MIT.Obtengo_Parametro (1 ,'ARCH_TEMP',1) para que recupere el temporal del linux.

**Comment by MarceloBellaera** [comment]
Seguimos con problemas , hicimos distintas pruebas pero siempre me da error.

el parametro que seteado a :/u01/app/dufry/temp 

![screenhunter_37 nov 10 17 45](https://cloud.githubusercontent.com/assets/23343058/20193675/d877ba3e-a76d-11e6-90de-a8833d38e7f3.jpg)
![screenhunter_38 nov 10 17 46](https://cloud.githubusercontent.com/assets/23343058/20193678/db28e30c-a76d-11e6-8965-008a98ed0602.jpg)

**Comment by rleuzzi** [comment]
MIT.Obtengo_Parametro debería devolver /u01/app/dufry/temp/ (le falta la barra final).

**Comment by MarceloBellaera** [comment]
Pusimos la barra y da el mismo error. 
/u01/app/dufry/temp/

**Comment by rleuzzi** [comment]
Podrán subir la imagen de la consola?. Porque en la anterior se veia la falta de la barra.

**Comment by ppalavezzati** [comment]
![screenhunter_39 nov 11 11 07](https://cloud.githubusercontent.com/assets/23344175/20217619/698b83f2-a7ff-11e6-9aef-e449c8f90f13.jpg)

**Comment by MarceloBellaera** [comment]
El fmx del  form f_ofic_prod de Uruguay no estaba. Lo quise compilar pero me dio error en el procedimiento llena_combo.
![image](https://cloud.githubusercontent.com/assets/23343058/20219434/285e9afa-a808-11e6-981f-05237c44b756.png)

**Comment by rleuzzi** [comment]
Respuesta para el caso del form f_ofic_prod.fmb (por favor, crear un issue por caso a revisar, caso contrario se mezclan en un mismo issue varios temas y no se puede cerrar el caso).

Para compilar deben usar el script perteneciente al pais de la siguiente forma:

./compila_un_form_uy.sh uruguay/comercial_logistica f_ofic_prod.fmb baires bairesdfc dfc

donde el primer parámetro es la ruta desde el directorio exe, el segundo es el nombre del fuente y los siguientes los datos de conexión. Ya se genero el fmx correspondiente por lo que pueden testear el form.

**Comment by ppalavezzati** [comment]
Agrego los Prints con los mensajes nuevos..
![screenhunter_54 nov 16 12 19](https://cloud.githubusercontent.com/assets/23344175/20352933/e9eda7cc-abf7-11e6-960e-ec0cd6d1a1e1.jpg)
![screenhunter_55 nov 16 12 20](https://cloud.githubusercontent.com/assets/23344175/20352932/e9ec5caa-abf7-11e6-897d-37e2cff315f7.jpg)
![screenhunter_56 nov 16 12 20](https://cloud.githubusercontent.com/assets/23344175/20352936/e9f4edd4-abf7-11e6-88aa-35342c6fbbca.jpg)
![screenhunter_51 nov 16 12 18](https://cloud.githubusercontent.com/assets/23344175/20352931/e9eb725e-abf7-11e6-9ae9-f05ab0a32d6a.jpg)
![screenhunter_52 nov 16 12 19](https://cloud.githubusercontent.com/assets/23344175/20352935/e9f39c72-abf7-11e6-9006-5406d4e71bf7.jpg)
![screenhunter_53 nov 16 12 19](https://cloud.githubusercontent.com/assets/23344175/20352934/e9f2d94a-abf7-11e6-89bf-66ed3e0565ca.jpg)

**Comment by rleuzzi** [comment]
Marcelo se ve un espacio en blanco entre la ruta recuperada por la funcion de BD y la concatenacion con la subcarpeta quedando algo como "/u01/app/dufry/temp/ AEP/itemod.003". Podrás validar si la función de BD recupera un espacion en blanco al final de la ruta? o sea recupera
"/u01/app/dufry/temp/ "
y deberia recuperar
"/u01/app/dufry/temp/"

**Comment by MarceloBellaera** [comment]
Efectivamente , le pifiamos . Ahora anduvo , pero tenemos otro problema. Al hacer el FTP a la PC del cliente le cambia el formato , como si no tuviera fin de linea. Hice una prueba con WinSCP cambiando los preajustes a Texto  y anduvo.  Quizas habria que cambiar el modo en que hace el FTP el form.

**Comment by rleuzzi** [comment]
Ok, evidentemente es el tema Linux vs Windows. Lo revisamos y te avisamos, pero nos quedamos tranquilos que lo de webutil funciona bien.

**Comment by rleuzzi** [comment]
Vuelvan a testear, agregamos una conversión del archivo antes del ftp de webutil.

**Comment by ppalavezzati** [comment]
Hola , buenos días.
No solo sigue pando lo mismo, el formato no es correcto, su no que ahora parece  cuando lo convertimos en formato... una letra "r" al final de cada línea.
Ver imágenes.

![archivo generado](https://cloud.githubusercontent.com/assets/23344175/20391440/22ab8466-acb2-11e6-97b0-6cc517a8c79b.jpg)

![archivo convertido a formato dos con una r](https://cloud.githubusercontent.com/assets/23344175/20391431/1be5e4dc-acb2-11e6-8a08-d8cfff19fd47.jpg)

**Comment by rleuzzi** [comment]
Ok, revisamos el script de linux que corrige el carriage return y les avisamos.

**Comment by leoponti** [comment]
Por favor volver a testear, a la espera de sus comentarios

**Comment by ppalavezzati** [comment]
Hola, buenos días.
Ahora genera el archivo vacío.
Adjunto imagen
![screenhunter_140 nov 22 13 50](https://cloud.githubusercontent.com/assets/23344175/20533159/5b0eb4ba-b0bb-11e6-8e9c-8bc8c684f024.jpg)

**Comment by rleuzzi** [comment]
Ok, estamos revisando que comando de linux pueda funcionar. Los mantenemos al tanto.

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by ppalavezzati** [comment]
Ahora se ven bien.
Gracias.
