### ISSUE TITLE
Sistema Interlocales- Emision Vales

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#30]
[Vales locales_enviar.docx](https://github.com/leoponti/dufry/files/664071/Vales.locales_enviar.docx)
Hola Les paso el error

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Hola sigue igual no sale el reporte pero fíjate que me parece que no lo tenes al .rdf puede ser eso

**Comment by rleuzzi** [comment]
Si no existe el rdf.

	
	The report terminated with error: 
REP-110: File vale_inter_local_a4. cannot be opened. REP-1070: An error occurred while opening or saving a document. REP-0110: File vale_inter_local_a4. cannot be opened. .


Por favor enviarmelo por correo asi lo migramos y subimos.

**Comment by marisacoria** [comment]
Hola lo volvi a testear y no funciona, uds tienen el rdf? este form dispara el reporte vale_inter_local_a4 y r_listado_reserva (Bton Listado Reserva y Bton  Emitir) nos avisan?

**Comment by leoponti** [comment]
Volver a testear, ya fueron subidos los reportes que nos pasaron ayer.
