### ISSUE TITLE
Sistema Interlocales

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#31]
Te envio también por error de Reporte, Reimprimir Vales
[Reimprimir_Vales_enviar.docx](https://github.com/leoponti/dufry/files/664125/Reimprimir_Vales_enviar.docx)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Sigue igual da error , si seleccionas uno e imprimis te ese error que te adjunte el documento

**Comment by rleuzzi** [comment]
No existe el rdf.

The report terminated with error: 
REP-110: File vale_inter_local_a4. cannot be opened. REP-1070: An error occurred while opening or saving a document. REP-0110: File vale_inter_local_a4. cannot be opened. .

Por favor enviármelo por correo así lo migramos y subimos.

**Comment by marisacoria** [comment]
Sigue igual , lo migraron?

**Comment by marisacoria** [comment]
PErfecto
