### ISSUE TITLE
Sistema interlocales

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#32]
Hola les reenvio 
[Reclarmo 0800_enviar.docx](https://github.com/leoponti/dufry/files/664153/Reclarmo.0800_enviar.docx)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Como el botón salir esta deshabilitado lo que queda es cerrar de ahí y cierra el sistema, en Oracle 10  no cierra todo el sistema , solo el form. te adjunto pantalla al final , el anterior punto de iconos esta bien
[Uploading Reclarmo 0800_enviar.docx…]()
