### ISSUE TITLE
Form para Migrar

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#35]
Les paso por mail un form de Interbaires/Interlocal que me quedo pendiente.

Es fo_cierre_vale_interloc.fmb

**Comment by leoponti** [comment]
lo pasaron x mail?

**Comment by marisacoria** [comment]
Hola  este form no esta migrado

**Comment by leoponti** [comment]
Crearon el Issue pero nunca enviaron el fmb para migrar, envienlo x mail. Será migrado la semana que viene que actualmente estamos trabajando con la configuracion del Servidor Productivo

**Comment by marisacoria** [comment]
si te se envio ahí se ve el atach

**Comment by marisacoria** [comment]
pero si no lo tienen me avisas y lo mandamos juntos con otros

**Comment by leoponti** [comment]
por lo que veo no esta adjunto y no se pueden atachar archivos del tipo fmb x esta plataforma asique imposible ;) lo que sean fmb unicamente envio x mail

**Comment by marisacoria** [comment]
si te lo envio por mail me dice MArcelo, pero recién te lo volvió a reenviar

**Comment by leoponti** [comment]
Ya se remigro, confirmar x favor asi lo cerramos
