### ISSUE TITLE
Error al cargar un archivo excel Sistema Comercial

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#37]
Error al cargar un archivo excel de interfaces de cambios de precios en el modulo de Sistema Comercial.
Seguramente es el tema de leer estos tipos de archivos desde el Cliente...
Sistema Comercial, /utilidades/carga de p´rod. por Interfaz/
Adjunto imágenes 

Gracias

![screenhunter_218 dec 22 11 42](https://cloud.githubusercontent.com/assets/23344175/21429174/6b3f7fa2-c83c-11e6-8fcd-f18074d275cf.jpg)
![screenhunter_220 dec 22 11 42](https://cloud.githubusercontent.com/assets/23344175/21429195/7e40df60-c83c-11e6-9c1a-b7dbbd756673.jpg)

![screenhunter_221 dec 22 11 43](https://cloud.githubusercontent.com/assets/23344175/21429208/8e272af6-c83c-11e6-94ff-a0ef7db096d9.jpg)

![screenhunter_223 dec 22 11 43](https://cloud.githubusercontent.com/assets/23344175/21429220/9df1fd30-c83c-11e6-989d-1a1e2887718b.jpg)

![screenhunter_224 dec 22 11 43](https://cloud.githubusercontent.com/assets/23344175/21429227/a56ef216-c83c-11e6-86d1-099b0d29812f.jpg)

**Comment by leoponti** [comment]
Volver a testear

**Comment by ppalavezzati** [comment]
Hola Leo.
Sigue dando error y sigue haciendo el FTP al servidor. Recordar que tienen que leer del archivo cliente.
![screenhunter_230 dec 22 16 41](https://cloud.githubusercontent.com/assets/23344175/21438053/f2b23a8c-c865-11e6-909e-1ac2df5239e2.jpg)

![screenhunter_231 dec 22 16 42](https://cloud.githubusercontent.com/assets/23344175/21438057/f71986de-c865-11e6-8e5b-9074bdbc71de.jpg)

![screenhunter_232 dec 22 16 43](https://cloud.githubusercontent.com/assets/23344175/21438059/fbc2cfba-c865-11e6-9bd1-6d22ecc23e0d.jpg)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
listo funciona
