### ISSUE TITLE
Problema con archivo Excel - idem issue #37

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#38]

**Comment by ppalavezzati** [comment]
Sistema comercial/utilidades/relacion producto y sus tester.../relacionar interfase/cuando se carga el archivo...
Misma problemática que en el Issue  37

![screenhunter_226 dec 22 12 21](https://cloud.githubusercontent.com/assets/23344175/21430428/f931e3b8-c841-11e6-8226-9214fdb0c7c2.jpg)

![screenhunter_227 dec 22 12 21](https://cloud.githubusercontent.com/assets/23344175/21430443/0a4037b8-c842-11e6-8280-e9cd1d775838.jpg)


![screenhunter_229 dec 22 12 21](https://cloud.githubusercontent.com/assets/23344175/21430487/25b1e71c-c842-11e6-9501-6b37ffe3f1a3.jpg)

**Comment by leoponti** [comment]
volver a testear

**Comment by ppalavezzati** [comment]
Idem caso anterior

**Comment by rleuzzi** [comment]
Volver a revisar.

**Comment by marisacoria** [comment]
Hola Leo , Ruben , esto lo pueden cerrar .
