### ISSUE TITLE
Sist, Interlocales

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#39]
Hola , les envio un error al ejecutar reporte, los reportes existen, tal vez el form llama al .rep

[Expediente interlocales Listados_enviar.docx](https://github.com/leoponti/dufry/files/669670/Expediente.interlocales.Listados_enviar.docx)

**Comment by leoponti** [comment]
Por favor indicar el fuente en cuestion para revisar

**Comment by marisacoria** [comment]
adm_destruccion, el fmb lo tendrías en las carpetas de interbaires/administracion
Acceder a Interlocales/expediente destrucción/ despliega otro menú y ahí ingresar al menú Listados, se disparan tres listados

**Comment by leoponti** [comment]
El fmb estaba en interbaires/logistica/administracion
Volver a probar nuevamente ya se corrigio

**Comment by marisacoria** [comment]
una consulta vos copiaste el fmb en la carpeta de interlocales? porque yo solo pase el .fmx y asi mantenemos una única versión y dejamos el fmb en logistica

**Comment by leoponti** [comment]
Si para compilarlo correctamente en el modulo en cuestion, preferis que quede el fmb en logistica?

**Comment by marisacoria** [comment]
si mejor que le fmb quede en logística y el fmx se copie a interlocales y también en logística que también lo usa.gcias

**Comment by leoponti** [comment]
Listo, confirmar todo y lo cerramos

**Comment by leoponti** [comment]
Marisa confirmame que esta ok este asi lo cerramos

**Comment by marisacoria** [comment]
si puse solucionado
