### ISSUE TITLE
Acceso directo para un form especifico

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#4]
Hola Ruben/Leo , tenemos algunos forms que los accedemos directamente sin pasar por ningun menu.   Anteriormente  accediamos con &form=  en el link.   Como se hace ahora con los archivos jnlp?

Saludos,
Marcelo.

**Comment by rleuzzi** [comment]
Marcelo depende de que pll's o olb's tenga referenciados. Si es un form que se asocia con, por ejemplo, recursos humanos de ecuador, y se llama "pepito" podrías acceder desde:

http://130.120.110.201:7777/forms/frmservlet?config=ec_rrhh&form=pepito.fmx

Si colocas esta url en el browser (Chrome te invitara a bajar el jnlp que te crea en el momento e IE corre directo) vas a poder acceder al fuente especifico.
