### ISSUE TITLE
Objetos a Migrar InterBaires

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#40]
Los  archivos los paso por mail haciendo referencia a este reclamo para  un mejor seguimiento.

Saludos,
Marcelo.

**Comment by MarceloBellaera** [comment]
Le agrego estos  objetos:

r_listado_reserva.rdf  	 (Interbaires)
stk_suc.rfd 			(Interbaires)
vta_suc.rdf	 		(Interbaires)

f_consultas_int.fmb    ( Interbaires/Interlocal)

**Comment by leoponti** [comment]
Ya se subio todo, volver a probar

**Comment by leoponti** [comment]
confirmar asi lo cerramos

**Comment by marisacoria** [comment]
EStos fuentes y reportes  de Interlocales ya están probados 
 r_listado reserva es de Vales a locales
consulta de int ejecuta los reportes de stok y vta
ya estan Probados
