### ISSUE TITLE
Sistema Administracion-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#44]
Hola 
No recupera el SERVICIO en el login de acceso al Sistema
SI NO COLOCA F5 NO PERMITE INGRESAR, y hoy solo se utiliza esa tecla para cambiar de usuario
[Acceso al Sistema.docx](https://github.com/leoponti/dufry/files/674101/Acceso.al.Sistema.docx)

**Comment by marisacoria** [comment]
tienen alguna novedad sobre este tema? no permite ingresar la base , y tiene que tocar la tecla F5 para que se habilite, en cambio en nuestro sistema la tecla F5 solo se utiliza en caso de que quiera cambiar de usuario

**Comment by marisacoria** [comment]
Hola Ruben te adjunto porque razón no funciona el acceso. creo que ya no tenes info del . env

**Comment by rleuzzi** [comment]
No llego nada adjunto.

**Comment by marisacoria** [comment]
ahí te lo adjunto
[Acceso al Sistema_PENDIENTE.docx](https://github.com/leoponti/dufry/files/709182/Acceso.al.Sistema_PENDIENTE.docx)

**Comment by rleuzzi** [comment]
Perfecto, por favor pasame el valor de la entrada DNS y lo agrego al environment del sistema de administración. Si es necesario agregarlo a algun otro sistema avisame.

**Comment by marisacoria** [comment]
Interbaires

**Comment by rleuzzi** [comment]
Se agrego entrada DNS=Interbaires en archivo environment de Administracion. Volver a revisar.

**Comment by marisacoria** [comment]
Hola Ruben! estoy en ambiente de prueba y funciona pero me esta recuperando el dns = interbaires, debería recuperar el de Desarrollo en este caso inter2 automáticamente, si es algo que podemos modificar nosotros nos pasas como se hace ? 
Gracias

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Listo ya funciona .gcis
