### ISSUE TITLE
Sistema ADministracion

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#48]
Hola les presento un Caso en el documento , en resumen el form llama a programas .NET y llamada a una web del afip , quería que vieran el código para saber si habría algún problema con esta llamada ya que no se puede testear para pruebas.
gracias

**Comment by marisacoria** [comment]
me olvide de adjuntársel
[Emitir Factura_llama al AFIP_consultar.docx](https://github.com/leoponti/dufry/files/675725/Emitir.Factura_llama.al.AFIP_consultar.docx)
os ahí va!

**Comment by rleuzzi** [comment]
WEB.SHOW_DOCUMENT funciona igual que las versiones anteriores asi que no deberia generar problemas.

**Comment by marisacoria** [comment]
ok listo
