### ISSUE TITLE
Sistema Administ-Solicitud Fact/Listados

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#49]
Por iconos
[Listados icono.docx](https://github.com/leoponti/dufry/files/675729/Listados.icono.docx)

**Comment by rleuzzi** [comment]
El icono de ese boton es el "rt_help" y nunca fue informado. Tengan en cuenta que agregar un icono implica generar nuevamente la Jar y firmarla con los certificados adquiridos así que si desean modificar la Jar les pediría chequeen todos los iconos que necesitan agregar asi ejecutamos el proceso solo una vez.

**Comment by marisacoria** [comment]
Wow! falta el escribano entonces tantas firmas jajaj, bueno estoy viendo que otros fuentes sin que se vean los iconos te los paso a todos juntos en otro isuue si?

**Comment by rleuzzi** [comment]
Jajaja si es un embole pero para que funcione el java es necesario. Porfa enviame mejor todos los iconos que entiendas faltan para ya trabajar sobre la regeneracion de la JAr.

**Comment by marisacoria** [comment]
okys perfecto prepara el escribano jajaj ,cerra este isue y te mando uno con pantalla que no se ven los iconos si te falta alguno me avisas y asi te los mandamos

**Comment by rleuzzi** [comment]
Si son iconos de la toolbar no los envies porque eso es otro tema de mayusculas en los nombres en alguna olb (se corrige recompilando). Solo los forms donde no se ven iconos de botones en pantalla. Porfa agrega nombre del form o como llegamos a el desde el menu correspondiente.

**Comment by marisacoria** [comment]
ahí van son toolbar pero dentro del mismo form, no se igual te los envio y otros desde el menú vertical como veníamos haciendo, por las dudas los mando, cada pantalla con el acceso
[Liquidaciones.docx](https://github.com/leoponti/dufry/files/675773/Liquidaciones.docx)

**Comment by marisacoria** [comment]
De este ultimo documento , el único  que falta los iconos es la ultima pantalla de Tablero de Control

**Comment by marisacoria** [comment]
este puedo probarlo?

**Comment by rleuzzi** [comment]
Los iconos están en minúscula. Volver a revisar. Si continua el error indicar usuario/password para probar en inter2.

**Comment by marisacoria** [comment]
listoo!!!cerralo
gcias
