### ISSUE TITLE
Remigrar Menu Logistica/Administracion

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#5]
Ruben , el menu de Logistica/Administracion no seria la ultima version.   Para no revisar los envios anteriores  te lo vuelvo a  mandar.

El path al que pertenece seria : 
/InterBaires/Logistica/Administracion

No me deja adjuntar  el archivo por aca , puede ser ?? Te lo mando por mail ??

**Comment by rleuzzi** [comment]
Hola Marce, podes adjuntar archivos por drag and drop (arrastra el archivo hasta el comentario y te arma el link). Saludos...

**Comment by MarceloBellaera** [comment]
Me dice que no soporta el  tipo , lo compacte como Zip y tampoco

**Comment by rleuzzi** [comment]
Si tenes razon. Mandamelo por correo y lo remigramos.

**Comment by rleuzzi** [comment]
Remigrado.
