### ISSUE TITLE
Sist Administracion-Faltan generar fmx?

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#50]
Faltarian los fmx siguientes , solo están los fmb, los pueden compilar o faltan migrar?

   F_exenciones_prov_comi.fmx
   Comitente.fmx

**Comment by leoponti** [comment]
Comitente.fmx ya generado, volver a probar.
Al otro se lo esta revisando pq no compila

**Comment by leoponti** [comment]
Volver a probar ambos x favor, y dar el ok

**Comment by marisacoria** [comment]
Listo cerrar
