### ISSUE TITLE
Sist-Interlocal -No sale el Reporte-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#51]
[Vales de salida WEB.docx](https://github.com/leoponti/dufry/files/677635/Vales.de.salida.WEB.docx)

**Comment by leoponti** [comment]
Volver a testear

**Comment by marisacoria** [comment]
Hola Leo esto sigue igual no sale el reporte ahí te adjunto prueba y el job de reportes

**Comment by marisacoria** [comment]
este me parece que esta por discontinuarse déjame ver. gracias.

**Comment by leoponti** [comment]
avisanos asi lo cerramos cualquier cosa

**Comment by marisacoria** [comment]
Este reporte no sale porque en el form fo_vales_web.fmx tiene otra fecha mas reciente del 28 de diciembre que esta en la carpeta logística/reposicion  y resulta que en interlocales compartiría el mismo fmx y resulta que esta con otra fecha vieja del 01/12 , si lo podes pasar el mas nuevo  y me avisas y vuelvo hacer la prueba.?
gcias

**Comment by marisacoria** [comment]
Puedo probar esto?

**Comment by marisacoria** [comment]
Pueden revisar esto? me avisan si esta migrado lo que se ve en logística/reposicion , asi lo puedo copiar a interlocales?

**Comment by rleuzzi** [comment]
Listo, volver a testear. Recordar cuando nos solicitan arreglar un form, indicarnos si el fmx debe ser copiado a otro directorio porque no conocemos el aplicativo por lo que jamas al generar un fmx lo colocamos en otra carpeta (otro sistema).

**Comment by marisacoria** [comment]
listo cerralo funciona
