### ISSUE TITLE
Sist-Interlocales- sin acceso al form-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#53]
Hola : Por cannot read form  te adjunto acceso
[Cierre de VAles.docx](https://github.com/leoponti/dufry/files/677667/Cierre.de.VAles.docx)

**Comment by leoponti** [comment]
Este form, no fue pasado para migrar

**Comment by marisacoria** [comment]
Hola en los últimos mail de MArcelo te lo envió

**Comment by marisacoria** [comment]
si no los tenes te lo envio

**Comment by leoponti** [comment]
Volvelo a enviar por favor a Ruben con copia a mi, Gracias

**Comment by marisacoria** [comment]
este ya te lo pase por mail hoy

**Comment by marisacoria** [comment]
ya se migro?

**Comment by marisacoria** [comment]
Este sigue igual no accede al form .fmx

**Comment by marisacoria** [comment]
Este lo migraste ya ? asi lo probamos

**Comment by rleuzzi** [comment]
Listo Volver a testear.

**Comment by marisacoria** [comment]
Listo funciona gracias
