### ISSUE TITLE
Sistema Interlocales-sin acceso form-(Rev.Discont)

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#54]
También Cannot read form
te adjunto pantalla
[Pedidos al deposito.docx](https://github.com/leoponti/dufry/files/677668/Pedidos.al.deposito.docx)

**Comment by leoponti** [comment]
Podrian verificar si este form lo tienen compilado en 10? ya que no estaria compilando por un problema en un Trigger, para asegurarnos. Gracias

**Comment by marisacoria** [comment]
en espera pero si tenees razon

**Comment by marisacoria** [comment]
DISCONTINUADO .  lo pueden cerrar
