### ISSUE TITLE
17-CCAA-Compra Anticipada-Reporte

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#55]
Hola como están?
 Les adjunto este tema que no esta solucionado el reporte da error.
[control ccaa_enviar.docx](https://github.com/leoponti/dufry/files/680806/control.ccaa_enviar.docx)

**Comment by leoponti** [comment]
corregido, volver a testear

**Comment by marisacoria** [comment]
Listo para cerrar. Ya anda
