### ISSUE TITLE
17-CCAA -Compra anticipada- Falta fmx

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#56]
Hola buenas.
  Les paso un acceso, no se si falto migrar porque no se encuentra el fmx

gcvias.
[Resumen de vales.docx](https://github.com/leoponti/dufry/files/680819/Resumen.de.vales.docx)

**Comment by leoponti** [comment]
No compila porque no existe la columna FCH_TICKET en la tabla

**Comment by marisacoria** [comment]
entonces? ya lo pruebo?

**Comment by leoponti** [comment]
No, no va a compilar por ese error que informe anteriormente. Deberían revisar la tabla que contenga esa columna

**Comment by marisacoria** [comment]
oK. cerrarlo porque en F10 tampoco funciona , de ultima lo modificamos nosotros, solo déjalo migrado al fmb y listo.
gcias
