### ISSUE TITLE
Sistema Logistica -Administracion -Solicitudes al Proveedor

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#57]
Hola no se disparaon los reportes según documento adjunto
[Reportes_Solicitud Proveedores.docx](https://github.com/leoponti/dufry/files/694427/Reportes_Solicitud.Proveedores.docx)

**Comment by leoponti** [comment]
Volver a testear

**Comment by leoponti** [comment]
Listo, cerrado
