### ISSUE TITLE
Sistema Logistica - Administracion- Destruccion/Devolucin

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#58]
Hola como están?
 Les adjunto el documento con dos accesos por temas de iconos que no se ven en los menues 
[Circuito Desreservay etiquetas.docx](https://github.com/leoponti/dufry/files/699003/Circuito.Desreservay.etiquetas.docx)

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Listo Cerralo
gcias
