### ISSUE TITLE
Sistema 0800- bmp sin mostrarse-Produccion(falta enviar icono)

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#59]
[Test_0800_principal.docx](https://github.com/leoponti/dufry/files/699282/Test_0800_principal.docx)

**Comment by rleuzzi** [comment]
Nunca enviaron el bmp que no puede leer el sistema. Se le reclamo oportunamente. Por favor enviar el bmp faltante.

**Comment by rleuzzi** [comment]
Este lo cerramos o me pasan el icono?

**Comment by marisacoria** [comment]
cerralo casi no utilizan el sistma no importa. gciss
