### ISSUE TITLE
Error en  Reporte Logistica

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#6]
Buen dia , al emitir el reporte ( Verificacion / Adm de embarques ( Botos Listados )  obtenemos este error:

Error
	 	
	The report terminated with error: 
REP-110: File re_packing_list. cannot be opened. REP-1070: An error occurred while opening or saving a document. REP-0110: File re_packing_list. cannot be opened. .
 	 
Me parece que faltan todos los reportes de logistica. No puedo acceder al FTP de Sitnergia para revisar los envios ( da error ).

**Comment by rleuzzi** [comment]
Nunca fue informado ese reporte. En la imagen se detallan los reportes de Interbaires que nos informaron y se migraron:

![image](https://cloud.githubusercontent.com/assets/14017610/20390997/161fef68-acb0-11e6-992a-f11b6f76615a.png)

**Comment by MarceloBellaera** [comment]
Tendria que pasarte los reportes de Logistica , los hacemos por el FTP o por mail ?

**Comment by rleuzzi** [comment]
Mandamelos en un zip por correo.

**Comment by ppalavezzati** [comment]
El Zip esta enviado.
Esperamos tu confirmación ya que mientras avanzamos con los test, hay mas reportes y estos dan error.
Gracias.

**Comment by leoponti** [comment]
por favor volver a testear los reportes

**Comment by MarceloBellaera** [comment]
Probamos el listado de picking y dio este error:
	
	The report terminated with error: 
REP-110: File r_picking_agr.rep cannot be opened. REP-1070: An error occurred while opening or saving a document. REP-0110: File r_picking_agr.rep cannot be opened. .

Rervisamos el directorio y  encontre el  .rdf , pero el error hace referencia al .rep , deberian estar los reportes compilados tambien ?

Otro  reporte funcionó bien , este fue la reimpresion de bonos ( logistica )  re_ingreso_compra ( solo estaba el  rdf ) Sera que lo llama sin especificar la extensión ?

**Comment by rleuzzi** [comment]
Si el tema es que lo están lanzando con la extensión (en este caso .rep). Indiquenme que form lanza el reporte que no funciono y le eliminamos a la llamada la extensión.

**Comment by MarceloBellaera** [comment]
Eso quiere decir que vamos a tener que revisar todos los forms que llamen con la extension ??  En este caso  fue el form f_agrupar_pedidos de Logistica / Reposicion de IB.

Fijate que hicimos otra prueba con el de Logistica / Reposicion /  Opcion Comprobantes - Vales por Carro ( f_vales_por_carro ) que no indica la extension pero no lo pudo abrir y el archivo rdf si esta ( r_vale_canasto_A4_lote)

**Comment by rleuzzi** [comment]
Lo podemos revisar nosotros o generar el rep para todos (esto no lo aconsejo porque es mejor ejecutar el rdf en lo que respecta a performance). Igual no creo existan muchas llamadas con extensión. Revisamos el tema del r_vale_canasto_a4_lote.

**Comment by rleuzzi** [comment]
Existen varias formas que son difíciles de controlar porque toma el nombre del reporte de un radio button o usa la librería utilidades en vez de usar la librería estandar lib_package_rep. Se corrigieron varios casos que vimos en llamadas desde menúes y otras de algunos forms pero vemos que tambien los nombres con alguna letra en mayúscula y con extensión "rep" se recuperan de tablas como la tabla "mit.sto_comprobantes_nivel". Necesitamos corrigan esos valores en la tabla y vayan testeando los reportes si alguno no funciona nos indiquen el nombre del  form desde donde se lanza el reporte.

**Comment by ppalavezzati** [comment]
Hola, buenos días.
Después de tu mail a Marcelo, volví a probar algunos reportes y salen ok.
Solo nos queda una duda, se puede configurar como predeterminado algún navegador para sacar el reporte? Hoy día salen automáticamente por el Explorer de Win. 
En cambio ahora solicita seleccionar el navegador para abrir el reporte.
Ver imagen
Gracias.
![screenhunter_169 dec 01 12 35](https://cloud.githubusercontent.com/assets/23344175/20800662/04c0dfb4-b7c5-11e6-948f-c20535725341.jpg)

**Comment by rleuzzi** [comment]
Por lo que vimos es tema de configuración en la PC del usuario, cambiando que aplicación predeterminada quieren utilizar. Pueden ver el siguiente link que da una idea como elegir que programa elegir para que ya no vuelva a preguntarnos. Recomiendo revisarlo con tecnología para que quede como una tarea a ejecutar en la PC del usuario.

http://tecno-co.blogspot.com.ar/2012/11/cambiar-con-que-aplicacion-se-abre-algo.html

**Comment by ppalavezzati** [comment]
Hicimos lo que vos recomiendas y nos sigue solicitando que seleccionemos el programa para abrir el reporte.
![image](https://cloud.githubusercontent.com/assets/23344175/20926280/3fb22ed8-bb9a-11e6-8a00-f3e61219ae33.png)

![image](https://cloud.githubusercontent.com/assets/23344175/20926296/53ca7952-bb9a-11e6-8044-694a52dd82b0.png)
