### ISSUE TITLE
Puesta en producción sistema 0800

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#60]
Hola , buenos días.
Tenemos problemas para ingresar al sistema 0800, recientemente pasado a producción.
}Error: No se pueden ingresar al sistema. adjunto imagen con el mensaje...
![screenhunter_233 jan 12 09 42](https://cloud.githubusercontent.com/assets/23344175/21890273/b7db29a4-d8ab-11e6-8fac-713316aeda1f.jpg)

**Comment by rleuzzi** [comment]
La conexion con el usuario BAIRES no tiene inconvenientes:

![image](https://cloud.githubusercontent.com/assets/14017610/21890830/595d3446-d8ae-11e6-8253-3c25f28ff8fb.png)

Validar con desarrollo control de usuario/password.

**Comment by ppalavezzati** [comment]
Listo, ahora si.
Gracias.
