### ISSUE TITLE
Sist- Administracion- gnerarr excel de Packs-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#62]
Hola , te adjunto el documento , esta fallando al intentar armar la hoja 2 
[excel pack_enviar.docx](https://github.com/leoponti/dufry/files/729697/excel.pack_enviar.docx)

**Comment by marisacoria** [comment]
Y este también 
gcias!

**Comment by leoponti** [comment]
Nos podrian enviar info de como replicar el error

**Comment by marisacoria** [comment]
Hola Leo , en el documento ahí tienen los datos para replicar el error y solamente ingresan esos datos y después el botón e inmediatamente les aparece el error

**Comment by marisacoria** [comment]
este pudieron replicarlo?

**Comment by rleuzzi** [comment]
Por favor volver a testear. Controlar bien los datos y realizar mas de una prueba porque modifique algo a nivel CLIENT_OLE2 y la idea es validar que todo funciona OK.

**Comment by marisacoria** [comment]
Funciona ok, gracias
