### ISSUE TITLE
SIST_Logistica -Deposito-PRIORIDAD

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#64]
Hola como están , les adjunto documento no sale reporte para filtro estado 100
[Lis_Stk_por proveedor_enviar.docx](https://github.com/leoponti/dufry/files/735608/Lis_Stk_por.proveedor_enviar.docx)

**Comment by rleuzzi** [comment]
Volver a revisar. Lo probamos en desa y sale sin problemas (aunque no recupera datos).

**Comment by marisacoria** [comment]
Hola Ruben , 
   A mi no me anda te adjunto las pruebas versus Oracle 10 
[Lis stk por proveedor Oracle10.docx](https://github.com/leoponti/dufry/files/757874/Lis.stk.por.proveedor.Oracle10.docx)

**Comment by marisacoria** [comment]
Con estado 100 no anda

**Comment by rleuzzi** [comment]
Yo lo ejecuto en dinter y funciona.

![image](https://cloud.githubusercontent.com/assets/14017610/22695226/cd5c3066-ed28-11e6-95fe-a348cf7eb7d2.png)

**Comment by rleuzzi** [comment]
Le cambie la propiedad de elasticidad a ese campo para ver si te ayuda pero acá sale bien. Testealo en otra maquina también por las dudas.

**Comment by marisacoria** [comment]
lISTO FUNCIONA , gracias!
