### ISSUE TITLE
Sist-Logistica-Recepcion

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#66]
Hola como están? el acceso es de Menu logística /recepción/ tablas
 Les adjunto por un icono. Luego nos tendrían que dar la receta para poder saber que hacer cuando agregas iconos ya que tengo entendido tiene sus particularidades.
[Adm cod barra icono.docx](https://github.com/leoponti/dufry/files/740012/Adm.cod.barra.icono.docx)

**Comment by rleuzzi** [comment]
Utiliza el icono "rt_close" que no existe en la Jar de iconos porque nunca fue informado.

![image](https://cloud.githubusercontent.com/assets/14017610/22662148/bf9c5c5a-ec86-11e6-8ce5-e007f2ba1628.png)

**Comment by rleuzzi** [comment]
Lo cierro este issue?

**Comment by marisacoria** [comment]
SI CERRALO , lo modifico yo 
gracias
