### ISSUE TITLE
SISTEMA -logistica -Reposicion-PRIORIDAD 0

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#67]
Hola ruben , 
    Este es un listado que yo selecciono varios carros en el check(prueben con dos selección de checks)
    Primero crei que era porque llamaba al reporte con la A en mayúscula, entonces lo modifique r_vale_canasto_A4_lote  por r_vale_canasto_a4_lote   pero resulta que no funciono. y me tira ahora un error poco simpático....ahí te adjunto los pasos en el docum
[vales por carro.docx](https://github.com/leoponti/dufry/files/751201/vales.por.carro.docx)
ento y lo que fui viendo

**Comment by marisacoria** [comment]
ojala q no sea nada complicado , el tema es que pensábamos implementar Logistica la semana que viene y sin esta pantalla no podríamos hacerlo es muy utilizada

**Comment by rleuzzi** [comment]
Pero el problema no es el reporte. El reporte salio bien. El tema es que estas intentando abrir un archivo en un directorio virtual (abrirlo a través del browser) y ese directorio virtual no existe en el weblogic.

No recuerdo como funcionaba esto en 10g. Se creo un directorio virtual?. Esto era para impresión directa con orarep?.

**Comment by marisacoria** [comment]
Ruben vuelvo a Probar esto?

**Comment by marisacoria** [comment]
Ruben volvi  a probar y sigue igual , puede ser que no entienda el rrpa? que tiene que abrirlo con PDF?
asi trabaja en Oracle 10

**Comment by marisacoria** [comment]
no será que en Linux no tiene el Acrobat y entonces no puede abrirlo

**Comment by marisacoria** [comment]
Porque genero el Archivo el en u01/..... etc y esta el rrpa pero no entiende tal vez que tienen que abrirlo con PDF y da el error :
Error 404--Not Found

From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:

10.4.5 404 Not Found

**Comment by rleuzzi** [comment]
Si pero el reporte sale ok, el problema es la extensión. Esto lo usaban para impresión directa?. Creo que en su momento creamos un mime type para estos casos no recuerdo bien es que fue hace mucho tiempo. Validame como lo usan así tengo claro que hay que hacer porque si debe salir como pdf no tiene sentido generar un rrpa (para eso generamos el pdf y listo). Porfa detallame bien el funcionamiento y porque generan un rrpa así veo que hacemos. Gracias!!!

**Comment by marisacoria** [comment]
Otro tema de consulta en Gral.
Consulta para saber Ruben, los reportes siempre tienen que estar en Minuscula no? y en algunos forms vi que uds tienen una función upper puede ser? 
con respecto a este form  hoy esta para la opción imprimir y eligen el lote  , pero déjame ver si lo siguen utilizando con esta opcion

**Comment by marisacoria** [comment]
Hola Ruben , estaba viendo el Show document y me quede pensando si el path que indica es correcto: /forms/temp ....ahí te paso todo el código del form vales_por_carro
SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_FILENAME,'r_vale_canasto_a4'||'_lote'); 
     SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_COMM_MODE,SYNCHRONOUS); 
     SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_DESTYPE,FILE); 
     SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_DESNAME,'/u01/app/dufry/temp/Vales_Canasto_Lote_'||to_char(pLote)||'.rrpa'); 
     SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_DESFORMAT, vc_runformat); 
     SET_REPORT_OBJECT_PROPERTY(v_report_id,REPORT_SERVER,vc_reportserver); 
     -- 
     vc_ReportServerJob:=RUN_REPORT_OBJECT(v_report_id, PL_ID); 
     -- 
     vc_rep_status     := REPORT_OBJECT_STATUS(vc_ReportServerJob); 
     -- 
     WHILE vc_rep_status in ('RUNNING', 'OPENING_REPORT', 'ENQUEUED') LOOP 
         vc_rep_status     := REPORT_OBJECT_STATUS(vc_ReportServerJob); 
     END LOOP; 
     -- 
     IF vc_rep_status='FINISHED' THEN 
         WEB.SHOW_DOCUMENT('/forms/temp/Vales_Canasto_Lote_'||to_char(pLote)||'.rrpa','_blank'); 
         
     ELSE 
         mensaje('mensaje_error','Fallo generacion del reporte','Atencion'); 
     END IF;

**Comment by marisacoria** [comment]
Hola Ruben  ,  me entro la duda: el show document  entiende ese path? o debe ir el mismo de arriba?.
Por otro lado te confirmo que pueden pasar el de Vales_a_locales , y Vales por Carro  a PDF en lugar que se arme el rrpa.
   Ambos fuentes abren en pantalla los PDF y de ahí ellos imprimen.
  Te cuento que el de Vales_a_Locales ayer lo modifique y en el :blk_control.rg_form , tiene el nombre del reporte y se lo cambie a Minuscula  pero aun asi no funciona .
Gracias!

**Comment by rleuzzi** [comment]
Hola, el show_document solo funciona si el directorio físico donde esta el archivo es ademas un virtual path (directorio que puede interpretar el Browser a través del servidor de aplicaciones). En este caso nunca creamos un virtual path en Weblogic así que nunca va a funcionar.

Si estan de acuerdo en vez de crear el rrpa, modifico para que salga el pdf como todos los reportes. Confirmame y realizo el cambio.

**Comment by marisacoria** [comment]
Te confirmamos pasar los fuentes  con PDF , tanto el de Vales a Locales como el de Vales por Carro

Gracias!

**Comment by marisacoria** [comment]
Alguna News sobre esto?

**Comment by rleuzzi** [comment]
Prueben este que lo puse para que salga como pdf (f_vales_por_carro.fmb)

**Comment by marisacoria** [comment]
Iupi!! funciona!!! gracias!

**Comment by leoponti** [comment]
Genial, lo cerramos!
