### ISSUE TITLE
Remigrar IB - Administracion 

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#68]
Hola Ruben , surgieron unos cambios   previos a la implementacion y necesitariamos remigrar estos objetos.  Abro el caso por aca para hacer el seguimiento pero te los mando por mail.

InterBaires/Administración
                    Interfac.fmb   (Genera una salida en txt )
                    Fact_oas_char_pdf.rdf
                    Liquido_producto.rdf
InterBaires/Comercial
                   f_abm_producto.fmb

**Comment by rleuzzi** [comment]
Listo, migrados y publicados en weblogic de DESA. Testearlo y avisarme para subirlos a PROD.
