### ISSUE TITLE
SISTEMA -Logistica Reposicion-

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#69]
Hola Ruben, 
 Mismo tema como el de Vales por CArros , esta armando un rrpa , recorda que genera N reportes , te adjunto caso
[vales a Locales.docx](https://github.com/leoponti/dufry/files/757566/vales.a.Locales.docx)

**Comment by rleuzzi** [comment]
Explicame el caso como en el issue anterior. Porque generan un rrpa en vez de un pdf.

**Comment by marisacoria** [comment]
Confirmado modificar para que llame PDF como el de VAles por Carro
gracias

**Comment by rleuzzi** [comment]
Listo, modificado, volver a revisar.

**Comment by marisacoria** [comment]
Ruben
   Funciono el de Vales A4 perfecto , falta poquito!! Pero fallo el que dice Aduana 

    Lo probe y vuelve a salir el error y esta llamando al reporte en Mayuscula

Por otro lado estoy viendo esto en el Modo de salida ( Impresora, Preview, PDF )
   Y veo que esta en Mayuscula Printer y también el Preview, podrá ser esto también que esta molestando ¿
 Fijate que yo siempre pruebo con esta opción (asi lo usan los usuarios) , igual probe con preview y no funciona
Te adjunto CAso
[Vales a locales a PDF enviar.docx](https://github.com/leoponti/dufry/files/764888/Vales.a.locales.a.PDF.enviar.docx)

**Comment by marisacoria** [comment]
Ahí te adjunte en el form :blk_control.rg_salida

**Comment by rleuzzi** [comment]
Marisa, ahi lo modifique. Volvelo a revisar y me avisas. Recuerden que hoy salgo de vacaciones.

**Comment by marisacoria** [comment]
Hola Ruben , en la semana vamos a precisar seguramente asistencia porque se implementa Logistica Bodega y Administración son los dos Sistemas mas cargados de reportes y archivos como vimos  con quien nos podemos manejar ya sea via telefónica ?

**Comment by marisacoria** [comment]
Hola Ruben se cuelga y en el servidor de reportes no dice ni mu..

**Comment by marisacoria** [comment]
espera no toques nada! me parece q salio

**Comment by marisacoria** [comment]
Salio!! PErfecto!! listo!

**Comment by marisacoria** [comment]
que era?

**Comment by marisacoria** [comment]
uy espera , que sale el reporte pero parece que queda algo lockeado en la base

**Comment by marisacoria** [comment]
todo bien cerralo , pero que cambiaste al final?

**Comment by rleuzzi** [comment]
Los rrpa eran para la opción printer pero por lo que me comentaste lo imprimían una vez que aparecía el pdf en el Browser asi que lo único que hice fue dejar que tanto por preview como por printer ejecute el mismo código. También le agregue el lower() a los nombres de los reportes.
