### ISSUE TITLE
generación de Archivo interface txt

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#7]
Este es un caso similar a un Issues anterior.
Continuando con el test de Abastecimiento llegue a un caso donde el sistema genera un archivo txt y  pdf , para enviarlo a un proveedor.
El tema es que el formato del archivo esta mal.
EJ:
![1_arch_mal](https://cloud.githubusercontent.com/assets/23344175/20437507/fc666000-ad92-11e6-9f46-9409bb261236.jpg)
![2_setea_ajuste_de_linea](https://cloud.githubusercontent.com/assets/23344175/20437509/fc685766-ad92-11e6-8d93-ce65c0457bd0.jpg)
![3_arch_ok](https://cloud.githubusercontent.com/assets/23344175/20437508/fc680e78-ad92-11e6-911b-c9a8c42eaf75.jpg)

**Comment by rleuzzi** [comment]
Por favor indicar el nombre del Form o el acceso desde el menu para poder identificar el programa a corregir.

**Comment by ppalavezzati** [comment]
Ok..
Sistema Logistica_IB
Menu principal/Administración/Recepción/Solicitudes al proveedor
Form= Solicitudes_Prov

Problema:
Al generar archivo al proveedor.
Genera un archivo txt con un formato no compatible (tal cual pasaba con los archivos de interfaces de precios del issue #3)
Ademas luego de generar el archivo, arma un PDF  y da error en el archivo , también da error al intentar mostrar el reporte ,  ademas lo manda x mail al proveedor también da error por que interpreta que el archivo esta vació.
Adjunto imágenes.

![1](https://cloud.githubusercontent.com/assets/23344175/20576559/258869a2-b19d-11e6-92b5-1ccf0ca72898.jpg)

![2](https://cloud.githubusercontent.com/assets/23344175/20576572/37b4966e-b19d-11e6-8d32-58476e5d88fb.jpg)

![3](https://cloud.githubusercontent.com/assets/23344175/20576585/3ea8eb0a-b19d-11e6-8e21-1c0ac01b775e.jpg)

![error_reporte](https://cloud.githubusercontent.com/assets/23344175/20576597/46d25bea-b19d-11e6-9f06-6c9889fde907.jpg)


![error al generar pdf](https://cloud.githubusercontent.com/assets/23344175/20576600/4b29b18e-b19d-11e6-9ace-f02b7d583994.jpg)
![error al mandar mail](https://cloud.githubusercontent.com/assets/23344175/20576601/4b3d9ce4-b19d-11e6-9328-977f766f0c96.jpg)





Gracias.

**Comment by MarceloBellaera** [comment]
Mail de Ruben:
"Marcelo en este issue vemos que se genera un pdf en el subdirectorio "Solicitudes_IOSC" pero nunca nos indicaron crear ese subdirectorio en el temporal del weblogic. Lo creamos no?. Hay otros subdirectorios que falten?"

"Por otro lado en test vemos que la función del BD aun devuelve el directorio de windows en DESA:
SQL> select MIT.Obtengo_Parametro (1 ,'ARCH_TEMP',1) from dual;
MIT.OBTENGO_PARAMETRO(1,'ARCH_TEMP',1)
--------------------------------------------------------------------------------
s:\duty\temp\"
Podran modificar ese valor por /u01/app/dufry/temp/  ?

-------------------------------------------------------------------------------------------------

Se modifica el parametro en desarrollo , si bien en testing ya estaba modificado.

Se crea el subdirectorio /u01/app/dufry/temp/Solicitudes_IOSC

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by MarceloBellaera** [comment]
El archivo de texto se genero bien pero  hay otros problemas que me imagino tienen que ver con la llamada el reporte al armar el directorio.
En el form arma el path con barra "\"  , es posible que esto genere problemas ??

	
	The report terminated with error: 
REP-69: An internal error occurred REP-56133: Access is denied to write to the specified location. .

**Comment by rleuzzi** [comment]
Listo volver a revisar. Faltaba agregar permiso de escritura a la nueva carpeta creada (Solicitudes_IOSC) en el archivo de configuración del servidor de reportes.

**Comment by ppalavezzati** [comment]
Hola , buenos días.
Sigue dando error en los permisos, al generar el reporte.
Adjunto imagen del OAS con el detalle.

![image](https://cloud.githubusercontent.com/assets/23344175/20886195/a12c7730-bad3-11e6-87d1-48c3803f532f.png)

**Comment by rleuzzi** [comment]
Por lo que pudimos ver existe un bug para permisos en mas de una carpeta:

![image](https://cloud.githubusercontent.com/assets/14017610/20888399/8fd53364-badd-11e6-981f-44bb4b53b2f3.png)

Volver a revisar, aplicamos una alternativa. Si no funciona deberemos aplicar el parche correspondiente al weblogic.

**Comment by MarceloBellaera** [comment]
Hola Ruben , teniamos un tema con el armado del path donde usamos la barra de directorios de windows, eso lo habian visto ?

**Comment by rleuzzi** [comment]
Eso se corrigio al inicio, fijate en la imagen del error que la ruta que muestra esta ok y es correcta las barras. El tema es que toma la ruta a temp pero no a la subcarpeta Solicitudes_IOSC. Por eso aplicamos una alternativa pero si no funciona deberemos aplicar el parche mencionado.

**Comment by MarceloBellaera** [comment]
Pero para la generación de interface de productos escribió en el subdirectorio "/temp/EZE" por ejemplo

**Comment by rleuzzi** [comment]
Pero ahi se genera el archivo por Text_io. No genera el archivo el servidor de reportes como en este caso. El problema es con el servidor de reportes.

**Comment by ppalavezzati** [comment]
Hola.
Esta ves salio el mail con los txt pero no el reporte del PDF. El mismo error.
![image](https://cloud.githubusercontent.com/assets/23344175/20890315/28cc7c42-bae5-11e6-8ade-5222ade76e8d.png)

**Comment by rleuzzi** [comment]
Vamos a proceder a aplicar el parche.

**Comment by ppalavezzati** [comment]
Ahora sale OK ¡¡

**Comment by rleuzzi** [comment]
Perfecto, funciono el parche. Cierro el issue.

**Comment by ppalavezzati** [comment]
![image](https://cloud.githubusercontent.com/assets/23344175/20939876/65408462-bbcf-11e6-8f57-09178240a48a.png)


![image](https://cloud.githubusercontent.com/assets/23344175/20939899/7d0a5410-bbcf-11e6-81d1-daa2e995a1dc.png)
