### ISSUE TITLE
Consulta por Report SErver Uruguay

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#70]
Hola ruben , para ver el seguimiento de Reportes Uruguay desa es otro ? o es el ..201  igual que para interbaires , por las dudas pregunto antes de comenzar a probar

**Comment by rleuzzi** [comment]
Es la misma url pero distinto el nombre del servidor. Al final de la url en vez de rep_desa pones rep_desauy o rep_desaec.

**Comment by marisacoria** [comment]
perfecto!

**Comment by marisacoria** [comment]
Tenes novedad de los vales por carro y Vales a locales? nos avisas cuando volvemos aprobar?
