### ISSUE TITLE
Uruguay - Compra anticipada

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#71]
como están?
  Hay una sola opción que no esta funcionando es la Entregados , las demás si.
Te adjunto caso
[Listado enviar.docx](https://github.com/leoponti/dufry/files/764636/Listado.enviar.docx)

**Comment by rleuzzi** [comment]
El fuente r_ant_entrega.rdf de interbaires es igual al r_ant_entrega.rdf de Uruguay?. El de interbaires anda bien y esta correcto el binario pero el de Uruguay no tiene grupos en el data model (mirando el fuente entregado por ustedes) por lo que jamas funcionara.

![image](https://cloud.githubusercontent.com/assets/14017610/22828583/d9127748-ef7c-11e6-9392-839cc42f3d80.png)

**Comment by leoponti** [comment]
Volvieron a testear este Issue? Confirmar así lo cerramos

**Comment by marisacoria** [comment]
cerralo lo arreglamos nosotros
