### ISSUE TITLE
Uruguay- Compra Anticipada-Consulta por BMP

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#72]
Hola Ruben
    Te Consulto lo siguiente, si yo te paso un BMP al Linux Desarrollo te tengo que avisar? en este caso el ccaa_locker.bmp es llamado desde el form principal de Compra anticipada y no estaba, entonces lo busque y te lo subi .

**Comment by rleuzzi** [comment]
Si podes subirlo sin drama (siempre en minúscula y en el directorio donde están los forms de ese modulo).

Saludos....

**Comment by marisacoria** [comment]
Si perfecto todo va en minúscula , gracias. y si fuera ICONOS ? ahí si te tengo que avisar para que lo adjuntes en el .jar no?

**Comment by rleuzzi** [comment]
Si si son iconos van a la Jar pero es todo un tema porque hay que regenerar la jar, firmarla y reiniciar el weblogic.

**Comment by marisacoria** [comment]
podes cerrarlo a este
