### ISSUE TITLE
Consulta por Error al ingresar al acceso- 

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#74]
Te adjunto el error que nos aparece en todos los accesos a los sistemas de ambiente desa
[Error en el acceso.docx](https://github.com/leoponti/dufry/files/771511/Error.en.el.acceso.docx)

**Comment by leoponti** [comment]
Marisa, es un tema de seguridad de ustedes, fijate que el cartel dice Connection Refused. CONEXION RECHAZADA

**Comment by marisacoria** [comment]
ahora les digo a los chicos gracias

**Comment by leoponti** [comment]
Marisa, estamos levantando todos los servicios, FORMS ya esta arriba, en unos minutos levantamos reports
