### ISSUE TITLE
como compilar en Inter2

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#75]
Hola Leo quiero compilar en la base inter2 , que tengo que configurar algo para poder compilar como lo hago con desa? tengo que crear una nueva sesión?
gracias!

**Comment by marisacoria** [comment]
Si me das un ayudita con esto porque generarlmente en la practica siempre compilamos con inter2 ó sino con poder compilar con INTER (Producción)

**Comment by leoponti** [comment]
Buenos dias Marisa, no hace falta configurar nada porque ya se encuentra inter2 en el tnsnames del server.
Te paso un ejemplo para compilar algo, y lo que tenes que hacer es cambiar la base x inter2

[oracle@interbwlogicd fmwconfig]$ cd $WRK_DIR
[oracle@interbwlogicd dufry]$ cd scripts/
[oracle@interbwlogicd scripts]$ ./compila_un_form_ib.sh interbaires/logistica/reposicion f_vales_locales.fmb baires bairesdesa dinter
