### ISSUE TITLE
Servidor Reportes Uruguay

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#76]
Hola Leo , como estas?
       No consigo ver el servidor de reportes cuando tira error 
es este el path correcto?http://130.120.110.201:7777/reports/rwservlet/getjobid18?server=rep_desauy

**Comment by marisacoria** [comment]
Me dice solamente cuando falla el reporte  esto:
 
  REP-52251: The output of job ID 18 requested on Tue Feb 14 18:29:45 ART 2017 cannot be retrieved.<P>REP-51026: No output is generated for job 18.

**Comment by leoponti** [comment]
Marisa está incorrecta la URL que estás ingresando, en vez de poner getjobid se usa showjobs?server=......

**Comment by marisacoria** [comment]
lo tenes a mano , me lo pasas?

**Comment by marisacoria** [comment]
ahh okys

**Comment by marisacoria** [comment]
listo !gracias!
