### ISSUE TITLE
Uruguay-Sistema Comercial -Logistica

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#78]
Hola Leo  , como estas?
   Te quería comentar que en casi todos los forms esta dando error al querer cargar el logo y yo veo que en Linux esta el logo pero en minúscula y el error quiere leerlo en mayúscula por ahí es eso , el tema es que esta referenciado la carga del logo , aca te paso 
[Nivels falta.docx](https://github.com/leoponti/dufry/files/787521/Nivels.falta.docx)
un caso.

**Comment by marisacoria** [comment]
ahhh también fíjate que tiene un icono que no se ve

**Comment by leoponti** [comment]
Pasame detalles de como replico el error, y datos para ingresar al sistema

**Comment by leoponti** [comment]
Volver a probar e informar si da el error del jpg

**Comment by marisacoria** [comment]
Perfecto ya andan , gracias

**Comment by leoponti** [comment]
Ambos iconos se ven ahora? dame el ok y lo cerramos

**Comment by marisacoria** [comment]
Solo el del logo Principal funciona bien 
El otro icono no se ve todavia

**Comment by leoponti** [comment]
Perfecto, verifique la jar de los iconos y ese icono no esta, por lo que no lo pasaron cuando se creo la misma, enviarlo y en los proximos dias se recompilara la jar

**Comment by marisacoria** [comment]
te lo envio entonces
