### ISSUE TITLE
No se ve Icono Buscar en barra de Froms

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#8]
Esto sucede en todos los forms que fui abriendo.
No de ve la imagen de Lupa ni de impresión , en la nueva versión.
Te paso los dos ejemplos....
Así  se ve hoy día....
![bara de utilidades](https://cloud.githubusercontent.com/assets/23344175/20437884/5c041614-ad94-11e6-9548-6e6f99533b13.jpg)
Así se ve en el formato nuevo....
![pequenos iconos](https://cloud.githubusercontent.com/assets/23344175/20437956/9c6af40c-ad94-11e6-9af8-f37484c461c3.jpg)

**Comment by rleuzzi** [comment]
Verificamos y se ven correctamente los iconos de la toolbar. Por favor indicar caso concreto (Sistema, acceso desde menu o nombre form) para revisar el caso particular.

**Comment by ppalavezzati** [comment]
Hola , respecto a la toolbar, te comento que estoy probando los sistemas de logística IB y comercial IB .
En el sistema Comercial IB se ven bien y el sistema de logistica no.
En todos los casos en logistica ib , que aparece una toolbar,  no se ven ni la Lupa ni la impresora.
Fui entrando uno x uno a los forms de logística y pasa en todos.
Te tendría que pasar uno por uno, me parece que tiene que ser algo mas general.
Saludos.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by ppalavezzati** [comment]
Ahí se ben bien ¡¡
Gracias.
