### ISSUE TITLE
SIST uruguay -Comercial Logistica 

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#80]
Hola Leo , otro ejemplo de reporte que si bien en el log de reportes se ve bien generado, ocurre que en el momento que se lo llama , queda el explorer negro y colgado 
Si lo quiero ver desde el log de reporte : por ejemplo el job id 62 , se cuelga el explorer
te adjunto caso
Conectado con cmallo , ídem anterior caso , desde el mismo acceso de Menu pero otra opción :
[Comprobante express_se cuelgareporte.docx](https://github.com/leoponti/dufry/files/791420/Comprobante.express_se.cuelgareporte.docx)

**Comment by marisacoria** [comment]
Un Detalle , con la opción uno a uno , funciona ok, pero la opción Normal , se cuelga

**Comment by marisacoria** [comment]
ahí te mande un mail con datos para que pruebes este caso , me avisas ? solo opción normal

**Comment by leoponti** [comment]
Probamos y se abre correctamente:

![image](https://cloud.githubusercontent.com/assets/23220462/23615964/f2dad6a0-0266-11e7-8d15-6f619053779a.png)

![image](https://cloud.githubusercontent.com/assets/23220462/23615975/fb37803c-0266-11e7-95df-459ece316675.png)

**Comment by leoponti** [comment]
Por favor, probar en otro equipo.

**Comment by marisacoria** [comment]
Bueno Leo vayan probando esos casos similares y si les abre bien, me avisan y los vamos cerrando
mientras pruebo en otra pc

**Comment by marisacoria** [comment]
Se prueba hoy en otra pc . funciona bien. Cerralo
