### ISSUE TITLE
SIST-Uruguay - Recaudaciones-Reportes

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#81]
Hola Leo 
  Te quería preguntar un tema, si quiero compilar un reporte que scripts ejecuto ? porque quería compilarlo yo, para ver si andaba este tema que te adjunto en el documento ,resulta que da un error el reporte: no data found , y cuando lo abro el rdf no tengo problema compila (desde Report) , pero en Linux no veo ningún script para report : 
 cd scripts
[oracle@interbwlogicd scripts]$ ls
compila_forms_ec.sh  compila_menues_ec.sh  compila_plls.sh        compila_un_form_ib.sh  compila_un_menu_ib.sh
compila_forms_ib.sh  compila_menues_ib.sh  compila_una_pll.sh     compila_un_form_uy.sh  compila_un_menu_uy.sh
compila_forms_uy.sh  compila_menues_uy.sh  compila_un_form_ec.sh  compila_un_menu_ec.sh

**Comment by marisacoria** [comment]
ahora te adjunto ambos Casos por separado porque no me deja adjuntar dos doCumentos
[Recaudaciones_BtonDetalle_enviar.docx](https://github.com/leoponti/dufry/files/799301/Recaudaciones_BtonDetalle_enviar.docx)

**Comment by marisacoria** [comment]
El otro reporte que no sale tenes que presionar en la misma pantalla en el menú vertical con la impresorita

**Comment by leoponti** [comment]
Por favor indicar datos de acceso y a completar para llegar a replicar ese error

**Comment by marisacoria** [comment]
Este ingresas a al Sistema de recaudaciones, 
y haces f7 /f8 y tocar el botón detalle para ir a un reporte y te sale el error de job id :  
  REP-52251: The output of job ID 114 requested on Tue Mar 07 11:37:15 ART 2017 cannot be retrieved.<P>REP-51026: No output is generated for job 114.
  
 Otra prueba en la misma pantalla es : tocar la impresora que esta en el menú vertical y también sale esto

REP-52251: The output of job ID 115 requested on Tue Mar 07 11:39:29 ART 2017 cannot be retrieved.<P>REP-51026: No output is generated for job 115.

**Comment by marisacoria** [comment]
El acceso es Administración /
Recaudaciones
ingresan con baires/bairesdesa/dfc2

**Comment by marisacoria** [comment]
y los  reportes existen en sus respectivos directorios y están en minúsculas no se que puede ser

**Comment by marisacoria** [comment]
Se da por cerrado porque en Oracle 10 también pasa lo mismo
