### ISSUE TITLE
Sistema-Uruguay -RRHH-Adm empleados-ICONO

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#82]
Hola Leo te adjunto estas dos pantallas que no se ven los iconos
[Administracion de EMpleados_faltaICONO.docx](https://github.com/leoponti/dufry/files/799313/Administracion.de.EMpleados_faltaICONO.docx)

**Comment by marisacoria** [comment]
otra MAS -Jornada Laboral
[Jornada Laboral_icono.docx](https://github.com/leoponti/dufry/files/799315/Jornada.Laboral_icono.docx)

**Comment by leoponti** [comment]
Son iconos que no pasaron y no estan en la JAR de iconos. Si tenes los los nombres de imagen pasanoslo sino revisamos el form y se los pedimos

**Comment by marisacoria** [comment]
Hola Leo , 
 Ahí les pase el icono rt_help.gif para que lo incluyan en la jar. esta en  uruguay/rrhh/.
y resolvería ambos temas y asi cerraríamos RRHH de UY

**Comment by marisacoria** [comment]
pudieron hacer el jar con este icono?
slds!

**Comment by rleuzzi** [comment]
Marisa los adjuntos mandalos por mail porque por aquí no llegan.  Por otro lado recorda que regenerar la Jar es todo un tema porque hay que reiniciar todos los servicios así que vamos a tratar de hacerlo por la tarde.

**Comment by marisacoria** [comment]
Hola Ruben 
queremos saber si RRHH con los iconos ya estaría porque ya queremos largar Uruguay y Ecuador a Produccion y vemos que no falta mucho
gracias

**Comment by rleuzzi** [comment]
Marisa aun no recibimos el rt_help.gif por mail. Sin ese archivo no podemos regenerar la Jar.

**Comment by marisacoria** [comment]
Hola Ruben si hace tiempo se los envie, pero también observe que se los puse en el Linux desa , en uruguay y ecuador al .gif  te paso la ruta por mail

**Comment by leoponti** [comment]
Listo, ya fue recompilada la Jar, volver a testear asi lo cerramos

**Comment by marisacoria** [comment]
Listo cerralo!

**Comment by leoponti** [comment]
Ok cerrado
