### ISSUE TITLE
SIST -Uruguay -RRHH- Listados

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#83]
Hola Leo , te adjunto esta pantalla , solo la segunda opción el reporte no sale y se cuelga, aunque en el log de reportes lo muestra generado, pero el usuario no tiene acceso al este log y pensara que se colgo
[Segunda Opcion Listado_enviar_secuelga.docx](https://github.com/leoponti/dufry/files/799376/Segunda.Opcion.Listado_enviar_secuelga.docx)

**Comment by leoponti** [comment]
Por favor testear en otro equipo.

**Comment by marisacoria** [comment]
cerralo
