### ISSUE TITLE
Remigrar f_comprobante

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#84]
Necesitamos remigrar  f_comprobante de Uruguay.  Te lo pase por mail. 

Gracias,

**Comment by rleuzzi** [comment]
Listo, volver a testear. Solo se genero el fmx en la carpeta comercial_logistica de Uruguay (no sabemos si es el mismo archivo en Ecuador).

**Comment by marisacoria** [comment]
Probado ok
