### ISSUE TITLE
SISTEMA-Logistica Reposicion- Acceso Reposicion Automatica-Urgente Produccion

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#85]
Hola Ruben
    Tenemos un tema cuando el usuario selecciona la opción locales , no puede resolver el query y si hacen shift -F1 te dice que hay campos que requieren alias. Por las dudas se los dejo a uds. que lo revisen porque me llama la atención que en Oracle 10 no tenga el mismo problema con el alias, lo resuelve bien, te adjunto una pantalla de Oracle 10 y otra del migrado; no quiero modificarlo yo y por ahí hay algo mas que la migración precisa.
[Reposicion automatica_enviar.docx](https://github.com/leoponti/dufry/files/814280/Reposicion.automatica_enviar.docx)

**Comment by marisacoria** [comment]
Listo ya lo arreglamos!

**Comment by leoponti** [comment]
Perfecto, lo cerramos
