### ISSUE TITLE
Sistema ECUADOR -Comercial Logisiti-(Menu Bodega)Report server colgado

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#86]
Hola Ruben, Leo , 
    Al ejecutar el listado , levanta el explorador pero no lo muestra queda la pantalla negra como adjunto y en el servidor de reportes esta como que salio bien. Puede ser que sea algo de configuración del report server para uruguay y ecuador , porque parece ser lo mismo q pasa en Uy con algunos listados 
[Lsitado de picking.docx](https://github.com/leoponti/dufry/files/821178/Lsitado.de.picking.docx)

**Comment by marisacoria** [comment]
Tene en cuenta que le fmb es de uruguay. Son buenos comparten el fuente

**Comment by leoponti** [comment]
Por favor indicanos de subsistema pertenece ej: comercial-logistica

**Comment by leoponti** [comment]
por favor testear en otro equipo

**Comment by marisacoria** [comment]
cerralo
