### ISSUE TITLE
Sitema URUGUAY- Comercial -Logis- Listados de picking se cuelga(menu_bodega)

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#87]
Hola Ruben, 
    Te adjunto se trata del mismo fuente porque lo comparte con Ecuador , el fmb es de uruguay.
y el tema es el mismo abre el explorer pero queda colgado
[Listado picking_enviar.docx](https://github.com/leoponti/dufry/files/821258/Listado.picking_enviar.docx)

**Comment by leoponti** [comment]
Por favor indicarnos a que subsistema pertenece ej: comercial-logistica

**Comment by leoponti** [comment]
por favor testear en otro equipo

**Comment by marisacoria** [comment]
podes cerrarlo
