### ISSUE TITLE
Impresion comprobante Desreserva

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#88]
Hola Ruben ,  este form esta dando error al imprimir un reporte. Según creo es el PU  imprimir_lote_vales .
El form es   f_asignacion_picking.fmb

Lo podras ver ?? 

El error que da es :

Error 404--Not Found

From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:

10.4.5 404 Not Found

The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

Imagino que por el Show document.

Gracias,
Marcelo.

**Comment by marisacoria** [comment]
Hola Ruben este tema es posiblemente porq genera rrppa  y show document , si no anda lo hacen con llamada común en todo caso

**Comment by rleuzzi** [comment]
Volver a testear.

**Comment by marisacoria** [comment]
Hola Leo , funciona pero le quiero achicar la fecha porque no se ve(sale con ****), consulta, solo lo abro al reporte y lo guardo al rdf y ya estaría no? asi lo modificamos nosotros

**Comment by marisacoria** [comment]
por otro lado por este isue solo modificaron el form no? para saber que pasar a produccion

**Comment by marisacoria** [comment]
todavía no lo cierres a este

**Comment by marisacoria** [comment]
listo cerralo ya lo modifique quedo ok

**Comment by leoponti** [comment]
ok, cerrado
