### ISSUE TITLE
Problemas con el formato en reporte de  Vales

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#89]
Ruben , cuando  usan este reporte se les va del margen inferior y queda practicamente ilegible. Yo probe con los mismos datos el report original y sale bien. Te adjunto ambos PDF 

El reporte es r_Vale_Canasto_A4_Lote de IB/Logistica.

[Vales defasado.pdf](https://github.com/leoponti/dufry/files/828382/Vales.defasado.pdf)
[r_vale_Canasto_A4_Lote_OAS.pdf](https://github.com/leoponti/dufry/files/828383/r_vale_Canasto_A4_Lote_OAS.pdf)

Por las dudas te envio el reporte original por mail para que lo vuelvas a compilar.

**Comment by leoponti** [comment]
Pueden probar nuevamente lanzar este reporte y ver si sale bien ahora?

**Comment by MarceloBellaera** [comment]
Hola Leo , sigue igual.

**Comment by MarceloBellaera** [comment]
Queres que te pase un set de datos para que lo puedas probar desde ahi ?

**Comment by leoponti** [comment]
Si dale por favor pasamos datos así podemos probar

**Comment by MarceloBellaera** [comment]
Podes  probar con el lote 197867 , son los vales que te  pase en el pdf.

**Comment by leoponti** [comment]
Listo, volver a probar.
El reporte que lanzaba ese form no era el mencionado sino: r_vale_a4_aduana_lote.rdf por eso no se reflejaban los cambios realizados,
Avisar asi cerramos

**Comment by marisacoria** [comment]
Perfecto gracias , listo, es que lo probaba en report y se comportaba diferente , al salir a Linux se ve que agrandaba la fuente. cerralo 👍

**Comment by leoponti** [comment]
Perfecto, cerrado
