### ISSUE TITLE
frm_ventas falta fmx

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#9]
Faltaria el compilado del form de Interbaires / CTC / frmventas

**Comment by rleuzzi** [comment]
No compila porque no ve el objeto CTC.TARJETAS_E3

**Comment by MarceloBellaera** [comment]
Comentale todo lo que esta dentro  ELSIF :LST_EMPRESA = 3 THEN . La EMPRESA 3 ya no existe.
Gracias.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.
