### ISSUE TITLE
Sistema  Ecuador - Comercial Logistica - Lectura excel

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#90]
Hola Ruben 
     esto es con usuario MCALAHORRANO /123456 /dfc2
     acceso Gestion por DAi desde menú principal y Carga de Saldos DAI
    Resulta que cargas el archivo y se queda en Leyendo Excel ....
  Por mail te adjunto la pantalla junto con el archivo para cargar,

**Comment by marisacoria** [comment]
Por otro lado les cuento y ahí lo van a ver en el mail , que no se ve el logo_dfe.bmp y el archivo existe el tema es que esta con mayúscula la E , por ahí por eso no lo levante

**Comment by rleuzzi** [comment]
Marisa, Marcelo habia indicado que el tema excel en Ecuador y Uruguay seria modificado el código para evitar este tema. Por favor validame esta situación.

**Comment by marisacoria** [comment]
Ruben,  
 Me dice Marcelo que en este caso lo precisa, y que sea leído desde el cliente.

**Comment by marisacoria** [comment]
Ya te lo mande por mail el Excel a cargar para las pruebas

**Comment by rleuzzi** [comment]
Y es que deberemos volver a analizar las otras alternativas que ya habían sido desechadas. O sea sera todo un tema en si.

**Comment by rleuzzi** [comment]
Listo, volver a revisar.

**Comment by marisacoria** [comment]
Perfecto cerralo

**Comment by leoponti** [comment]
ok, cerrado
