### ISSUE TITLE
Sistema Ecuador- Comercial Logistica-Desde Menu Listados-ICONOs

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#91]
Hola  Ruben , Leo 
   En estos documentos q te adjunto no se ven los iconos del menú vertical 
Te adjunto las pantallas por mail

**Comment by marisacoria** [comment]
Desde el menú listado , ambos accesos tienen el mismo tema con el icono en el menú vertical

**Comment by leoponti** [comment]
No se pueden adjuntar documentos x aca envianos x mail xfa

**Comment by leoponti** [comment]
Pasanos datos de acceso exactos para poder ingresar al sistema, recuerden ser siempre detallados ya que no conocemos la funcionalidad de los sistemas

**Comment by marisacoria** [comment]
Ahí te puse Desde el el menú listado / Listado stock etc.
                                                          /consulta e impresión tickets

**Comment by leoponti** [comment]
Y con que usuario/clave base ingreso?

**Comment by marisacoria** [comment]
Como se trata de iconos no precisas datos, solo observa que en el menú vertical no se ven los iconos

**Comment by marisacoria** [comment]
ingresa con MCALAHORRANO/123456 /dfc2

**Comment by leoponti** [comment]
Solucionado, volver a probar y avisar para dar cierre

**Comment by marisacoria** [comment]
Hola,  estaría faltando /consulta e impresión tickets que sigue igual, el otro ya se ven los iconos

**Comment by leoponti** [comment]
No existe ninguna opcion Consulta / impresion de tickets, estas segura que es con este mismo usuario? enviar captura x favor

**Comment by marisacoria** [comment]
Tendrías que verlo porque esta en la misma opción de Listados y se llama consuelta e impresión de tickets , sin la / 
acordate que el usuario es MCALAHORRANO
gcias

**Comment by marisacoria** [comment]
ya falta poco, ya se termina!:)

**Comment by leoponti** [comment]
Listo, quizas entre con otro usuario, pero no veia ese mismo menu jaja. Vuelvan a probar y lo cerramos

**Comment by marisacoria** [comment]
si segun el usuario te habilita distintas cosas . 
Listo cerralo!

**Comment by leoponti** [comment]
ok, cerrado

**Comment by marisacoria** [comment]
falta menos!jajj cuenta regresiva
