### ISSUE TITLE
SISTEMA ecuador- tema logo que se utiliza en todos los forms-Aviso

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#92]
Hola Ruben, 
   Te aviso que el logo logo_dfE.bmp que ya estaba en Linux desarrollo , le cambie el nombre a logo_dfe.bmp en minúscula para que se vean en los forms, pero te aviso para que lo tengas en cuenta si lo tenes que volver a compilar .

**Comment by marisacoria** [comment]
Me refiero a armar el .jar

**Comment by marisacoria** [comment]
les recuerdo que este logo le cambiamos el nombre  de Logo_dfE.bmp,  lo modificamos en Linux desarrollo a logo_dfe.bmp , no se si les afecta para amar el .jar pero les aviso

**Comment by rleuzzi** [comment]
Marisa, los logos no son parte de las Jar's. Comentame que forms tienen problemas en visualizar el logo y los revisamos.

**Comment by marisacoria** [comment]
Entonces para saber , si yo tengo un logo en el form principal y además otro logo que son referenciados en todos los forms del sistema(como encabezado), esto no afecta a la .jar ? De ser así solo afectaría a la JAR  aquellos que están como icono en un botón o bien en un Menu (nuestro menú vertical ) sin importar si es un .gif o un .jpg.
si me podes aclarar esto por fi

**Comment by marisacoria** [comment]
Por ahora los forms que no se visualizaban los pude arreglar teniendo el cuenta el tema de mayúsculas y minúsculas pero tengo esa duda

**Comment by rleuzzi** [comment]
En realidad en una Jar podes poner todo pero depende como programaste el form. En sus forms los logos estan en un campo image dentro de un bloque por ende busca la imagen en las rutas definidas en la FORMS_PATH. Por favor indicanos los forms que no se ve el logo así lo corregimos.

**Comment by marisacoria** [comment]
Bueno Ruben , ya los corregí , solo modifique el nombre de los archivos del logo a minúscula y ya se visualizan bien; pero por las dudas te avise que le cambie el nombre a minúscula y en las tablas en las que busca el nombre también , asi que era para que lo tengas en cuenta  , asi que lo podes cerrar.

**Comment by leoponti** [comment]
ok listo cerrado
