### ISSUE TITLE
Sistema de inventarios Uruguay

### ISSUE THREAD

**Issue by ppalavezzati** [leoponti/dufry#94]
Hola estoy testeando el sistema de inventarios UY y detecté el siguiente problema.
En el menu Inventarios/Interfaz matricero se genera un archivo Txt interfaz que va a ser levantado por unos colectores con los cuales tomaran el inventario.
No esta saliendo correctamente dicho archivo.
Adjunto ejemplo.
[Matricero_2136.txt](https://github.com/leoponti/dufry/files/839508/Matricero_2136.txt)

![screenhunter_370 mar 13 17 17](https://cloud.githubusercontent.com/assets/23344175/23873554/3237a94a-0811-11e7-9924-348cf4d071b5.jpg)

**Comment by marisacoria** [comment]
Hola Ruben , para recordarles un poco este error ya había ocurrido , el tema es que el archivo lo arma pero sin bajar de línea

**Comment by rleuzzi** [comment]
Listo, volver a testear.

**Comment by marisacoria** [comment]
Perfecto cerralo gcias!!

**Comment by marisacoria** [comment]
mira que este ya lo pueden cerrar

**Comment by leoponti** [comment]
Perfecto, cerrado, gracias
