### ISSUE TITLE
Sistema IB (Argentina) -Administracion - Listado

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#95]
Hola ruben , Leo , les voy a enviar como probar este tema , pero creo que ya había pasado en otro reporte
Sistema Argentina -Administración       con usuario cherrera/123456/inter2

**Comment by marisacoria** [comment]
se los mando por mail

**Comment by rleuzzi** [comment]
Volver a Testear.

**Comment by marisacoria** [comment]
Hola ya funciona , pero preciso saber si  tengo que pasar solamente el reporte a producción o también el form?

**Comment by rleuzzi** [comment]
Era problema con un campo texto del reporte. Se borro y se volvió a crear y funciono. No necesitas pasar nada porque ya refrescamos producción nosotros.
