### ISSUE TITLE
Sistema Logistica (Argentina) -Menu recepcion -por Listados

### ISSUE THREAD

**Issue by marisacoria** [leoponti/dufry#96]
Hola Ruben, 
   Este tema de de IB Logistica - Menu Recepción- los listados salen pero no reconocen el parámetro pasado de la bodega y entonces no trae datos, esto esta ocurriendo en Producción solo con el sistema migrado.
Te envio por mail detalles para que uds. puedan probar los casos.

**Comment by marisacoria** [comment]
Listo ya lo pude ver Ruben , no lo vean , yo lo corrijo. pueden cerrarlo

**Comment by marisacoria** [comment]
es un tema de minúsculas , mayúsculas del nombre del reporte , yo lo corrijo.

**Comment by leoponti** [comment]
Ok
