### ISSUE TITLE
RRHH Uruguay - Re migrar

### ISSUE THREAD

**Issue by MarceloBellaera** [leoponti/dufry#97]
Leo ,  encontramos un problema de versiones con  algunos forms de Uruguay. Son basicos y  no  tienen archivos de salida   ni nada fuera de lo standard, son todos  bloques basados. 

Te los paso por mail.

Gracias,
Marcelo.

**Comment by marisacoria** [comment]
Estos no tienen reportes son abm's , bueno después me avisan que cosa me podría estar faltando en la migración porque no se ven el menú vertical en IB ?

**Comment by rleuzzi** [comment]
Listo, remigrados y publicados en DESA. Testear e indicar cuando mover a PROD.

**Comment by marisacoria** [comment]
Ya funciona gracias!
